# Data parameters
# ==================================
tag: "tag_name"
mode: "online"
standardize: True
file_num: 1000

Ntrainpoints: 5000
Ntestpoints: 1000
number_of_noisy_obs: 5

# Model parameters
# ==================================
lstm_size: 128
latent_size: 20
input_size: 2 
seq_size: 150
num_lyears: 1
batch_size: 5
attention_size: 2
sample_reps: 20
directions: 2

# Not Used Yet
# ==================================
print_every: 1 #lower value, more often test/train loss print. Based on epoch
learning_rate: 1e-2
print_interval: 2
epochs: 8
lambda_kl: 0 #tune the prior? fit data vs. fit prior. Prior is zero mean gussian. try to set it to 0
lambda_max: 1
lambda_update_rate: 0.1
optimizer_choice: 'AdamW' #AdamW , #SGD
save_bad_img: "No" #Yes
eta: 0.01